# Site settings
title: Code Journey
email: leepaulwebdev24@gmail.com
description: A blog about my programming journey. 
baseurl: "/project-blog"
twitter_username: LeePaul24
avatar: "https://pbs.twimg.com/profile_images/900141991421329409/R36veEL-_400x400.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Lee Paul" # Set default author name
      categories: "learning"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
